language: nodejs

nodejs: 
  - stable

scripts:
  - npm install
  - npm test
  - npm build

deploy:
  provider: surge
  skip_cleanup: true
  domain: testdriven-deploymentbyahsen.surge.sh
  project: ./build/

on:
  branch: master

